# Generated by Django 2.0.2 on 2018-05-29 19:49

import basis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_moderated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(choices=[(basis.models.CountryTag('German'), 'German'), (basis.models.CountryTag('French'), 'French'), (basis.models.CountryTag('Japanese'), 'Japanese'), (basis.models.CountryTag('Thai'), 'Thai'), (basis.models.CountryTag('Canada'), 'Canada'), (basis.models.CountryTag('Chinese'), 'Chinese'), (basis.models.CountryTag('Swiss'), 'Swiss'), (basis.models.CountryTag('Indonesian'), 'Indonesian'), (basis.models.CountryTag('Spanish'), 'Spanish'), (basis.models.CountryTag('USA'), 'USA'), (basis.models.CountryTag('British'), 'British')], max_length=5)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basis.Country')),
            ],
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basis.User'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basis.Zone'),
        ),
        migrations.AddField(
            model_name='comment',
            name='point_of_interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basis.PointOfInterest'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basis.User'),
        ),
        migrations.AddField(
            model_name='category',
            name='point_of_interest',
            field=models.ManyToManyField(to='basis.PointOfInterest'),
        ),
    ]
