# Generated by Django 2.0.2 on 2018-05-30 01:34

import basis.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0002_auto_20180529_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='tag',
            field=models.CharField(choices=[(basis.models.CountryTag('German'), 'German'), (basis.models.CountryTag('French'), 'French'), (basis.models.CountryTag('Japanese'), 'Japanese'), (basis.models.CountryTag('Thai'), 'Thai'), (basis.models.CountryTag('Canada'), 'Canada'), (basis.models.CountryTag('Chinese'), 'Chinese'), (basis.models.CountryTag('Swiss'), 'Swiss'), (basis.models.CountryTag('Indonesian'), 'Indonesian'), (basis.models.CountryTag('Spanish'), 'Spanish'), (basis.models.CountryTag('USA'), 'USA'), (basis.models.CountryTag('British'), 'British')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
