# Generated by Django 2.0.2 on 2018-05-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0003_auto_20180530_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
