# Generated by Django 2.0.2 on 2018-05-30 01:59

import basis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0005_auto_20180530_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='tag',
            field=models.CharField(choices=[(basis.models.CountryTag('German'), 'German'), (basis.models.CountryTag('French'), 'French'), (basis.models.CountryTag('Japanese'), 'Japanese'), (basis.models.CountryTag('Thai'), 'Thai'), (basis.models.CountryTag('Canada'), 'Canada'), (basis.models.CountryTag('Chinese'), 'Chinese'), (basis.models.CountryTag('Swiss'), 'Swiss'), (basis.models.CountryTag('Indonesian'), 'Indonesian'), (basis.models.CountryTag('Spanish'), 'Spanish'), (basis.models.CountryTag('USA'), 'USA'), (basis.models.CountryTag('British'), 'British'), (basis.models.CountryTag('Phillipines'), 'Phillipines')], default='null', max_length=5),
        ),
    ]
