# Generated by Django 2.0.2 on 2018-05-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0006_auto_20180530_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
